### ISSUE TITLE
compat with turnip-2.1.0

### ISSUE THREAD

**Issue by munkyboy** [gongo/turnip_formatter#65]
based on the release notes for turnip-2.1.0, it seems turnip-formatter will be compatible. The turnip gem dependency version range should be updated to include 2.1.0.

**Comment by gongo** [comment]
Thanks for issue. I forgot verson up  :sweat_smile:

**Comment by gongo** [comment]
Hi @munkyboy 
I've released `turnip_formatter 0.5.0` that compat with `turnip 2.1.0` :smile:

**Comment by munkyboy** [comment]
great! thanks for the prompt action

**Comment by munkyboy** [comment]
also, thanks for updating gnawrnip too :)
