### ISSUE TITLE
Add support for RSpec::Core::MultipleExceptionError

### ISSUE THREAD

**Issue by JohnBat26** [gongo/turnip_formatter#84]
Hello.
When I get several exception during test execution then I see only:

```
Failure:
RSpec::Core::MultipleExceptionError
Backtrace:
```

But this class has @all_exceptions property with a array of all exceptions.
It would be nice print all exceptions in a html report instead RSpec::Core::MultipleExceptionError.

**Comment by gongo** [comment]
Hi @JohnBat26 

I guess that this problem is probably the same as GH-67 .
I'm trying to fix it at GH-83. Please wait until release 0.6.0 (not pre) 🙇

**Comment by JohnBat26** [comment]
@gongo  thanks for quick answer. We will wait for version 0.6. :)

**Comment by gongo** [comment]
Hi @JohnBat26 

I've released 0.6.0.pre.beta.5 that corrected this problem.
Please try this .

**Comment by JohnBat26** [comment]
Hi @gongo. I've tried this. While all works OK. Now I don't see MultipleExceptionError. Thanks. :)

**Comment by gongo** [comment]
💪
