### ISSUE TITLE
support for rspec >= 3.5.x

### ISSUE THREAD

**Issue by munkyboy** [gongo/turnip_formatter#92]
Why is rspec 3.5 not allowed?
https://github.com/gongo/turnip_formatter/commit/3c1a1a299c8c78e6431b7eb095f94632c27d4510

**Comment by gongo** [comment]
Hi @munkyboy 

> Why is rspec 3.5 not allowed?

I forgot to fix it to `~>3.5` .
I will fix it soon. 🙇

**Comment by gongo** [comment]
Hi @munkyboy 

I fixed and release [0.6.1](https://rubygems.org/gems/turnip_formatter/versions/0.6.1) that support RSpec 3.5 💪
